name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: ls
    - run: sudo apt install coreutils zutils cpio genisoimage
    - run: npm install electron-packager -g
    - run: echo "electron-packager=/opt/hostedtoolcache/node/14.17.3/x64/lib/node_modules/electron-packager/bin/electron-packager.js" >> $GITHUB_ENV
    - run: npm install electron-iso-packager -g
    - run: sudo /opt/hostedtoolcache/node/14.17.3/x64/lib/node_modules/electron-iso-packager/electron-iso-packager.sh . Arobic
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Arobic
        path: /home/runner/work/Arobic/Arobic/Arobic.iso
