name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: apt install coreutils zutils cpio genisoimage
    - run: npm install electron-iso-packager
